name: ardent-pos-app
services:
- name: web
  source_dir: /
  github:
    repo: mdYoungDOer/ardent-pos-project
    branch: main
  run_command: apache2-foreground
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /health.php
  envs:
  - key: APP_URL
    value: https://ardent-pos-app-sdq3t.ondigitalocean.app
  - key: DB_HOST
    value: db-postgresql-nyc3-77594-ardent-pos-do-user-24545475-0.g.db.ondigitalocean.com
  - key: DB_PORT
    value: "25060"
  - key: DB_NAME
    value: defaultdb
  - key: DB_USER
    value: doadmin
  - key: DB_PASS
    value: ${DB_PASS}
    type: SECRET
  - key: JWT_SECRET
    value: ${JWT_SECRET}
    type: SECRET
  - key: CORS_ALLOWED_ORIGINS
    value: https://ardent-pos-app-sdq3t.ondigitalocean.app
  - key: PAYSTACK_PUBLIC_KEY
    value: pk_test_af9bf6a2a8cf6ac7693e03ce00aeb5fdd48c25f3
  - key: PAYSTACK_SECRET_KEY
    value: ${PAYSTACK_SECRET_KEY}
    type: SECRET
  - key: SENDGRID_API_KEY
    value: ${SENDGRID_API_KEY}
    type: SECRET
  - key: SENDGRID_FROM_EMAIL
    value: notify@ardentwebservices.com
  - key: JWT_EXPIRY
    value: "3600"
  - key: API_URL
    value: https://ardent-pos-app-sdq3t.ondigitalocean.app/api
  - key: APP_DEBUG
    value: "false"
  - key: DEFAULT_CURRENCY
    value: GHS
  - key: DEFAULT_LOCALE
    value: en-GH
