name: ardent-pos
services:
  - name: frontend
    source_dir: /frontend
    github:
      repo: mdYoungDOer/ardent-pos-project
      branch: main
    build_command: npm install && npm run build
    run_command: npm run preview
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: VITE_API_BASE_URL
        value: ${backend.URL}
      - key: NODE_ENV
        value: production

  - name: backend
    source_dir: /backend
    github:
      repo: mdYoungDOer/ardent-pos-project
      branch: main
    build_command: composer install --no-dev --optimize-autoloader
    run_command: php -S 0.0.0.0:8000 -t public
    environment_slug: php
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /backend
    envs:
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_PORT
        value: ${DB_PORT}
      - key: DB_NAME
        value: ${DB_NAME}
      - key: DB_USERNAME
        value: ${DB_USERNAME}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: APP_URL
        value: ${APP_URL}
      - key: CORS_ALLOWED_ORIGINS
        value: ${CORS_ALLOWED_ORIGINS}

databases:
  - name: ardent-pos-db
    engine: PG
    version: "15"
    size: db-s-1vcpu-1gb
